toxic_keywords = [
    "rage",
    "flame",
    "carried",
    "carry",
    "flaming",
    "stupid",
    "hate",
    "toxic",
    "redesign",
    "item",
    "mythic",
    "coordination",
    "communication",

    "trolling",
    "feeding",
    "report",
    "throwing",
    "running it down",
    "run it down",
    "int",
    "AFK",
    "inting",
    "salt",
    "tilt",
    "BM",
    "noob",
    "OP",
    "nerf",
    "smurf",
    "ban",
    "GG",
    "MMR",
    "elo hell",
    "cancer",  # Commonly used as a metaphorical adjective, e.g: "low elo players are cancer to play with"
    "complain",
    "teammates",
    "unfair",
    "item",
    "balance",
    "lp",
    "broken",
    "bad team",
    "low elo",
    "bad",
    "suck",
    "frustration",
    "horrible",
    "awful",
    "ping",
    "no comm",
    "unbalanced",
    "disappointing",
    "annoying",
    "unplayable",
    "unenjoyable",
    "stuck",
    "harass",
    "negative",
    "hardstuck",
    "hopeless",
    "toxicity",
    "mute",
    "disconnection",
    "lag",
    "unresponsive",
    "imbalanced",
    "bug",
    "unbalanced",
    "pay-to-win",
    "annoyance",
    "unfun",
    "unpleasant",
    "stressful",
    "unsatisfying",
    "unrewarding",
    "unbearable",
    "cheater",
    "cheating",
    "exploit",
    "hacker",
    "uncompetitive",
    "imbalance",
    "trash",
    "unskilled",
    "unskilled player",
    "boring",
    "unlucky",
    "no fun",
    "unimpressed",
]


toxic_keywords = [word.lower() for word in toxic_keywords]

search_words = toxic_keywords


